repos:
- repo: https://github.com/gitleaks/gitleaks
  # Pinned tag; we'll update later with 'pre-commit auto-update'
  rev: v8.28.0
  hooks:
  - id: gitleaks
    # Optional: speed up by skipping large dirs (edit as needed)
    exclude: "(^dist/|^build/|^reports/)" 