repos:
  - repo: https://github.com/gitleaks/gitleaks
    # Pinned tag; we'll update later with 'pre-commit auto-update'
    rev: v8.28.0
    hooks:
      - id: gitleaks
        name: gitleaks (staged diff)
        args: ["--staged", "--redact", "--exit-code", "1"]
        pass_filenames: false
        stages:
          - pre-commit
          - pre-commit
          - pre-push # run on commit; pre-push optional

  # 2) Language-agnostic hygiene hooks
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: check-merge-conflict
      - id: detect-private-key
