name: openssf-scorecard

on:
  push:
    branches: [ "main" ]
  schedule:
    # Weekly on Fridays at 01:15 UTC (Saturday morning AEST)
    - cron: "15 1 * * 5"
  workflow_dispatch:

permissions: read-all

jobs:
  analysis:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      actions: read
      security-events: write   # upload SARIF to code scanning
      id-token: write          # required when publish_results: true
    steps:
      - name: Checkout (no persist creds)
        uses: actions/checkout@v5
        with:
          persist-credentials: false

      - name: Run OpenSSF Scorecard
        uses: ossf/scorecard-action@v2.3.3
        with:
          results_file: results.sarif
          results_format: sarif
          publish_results: true    # enables public badge via the Scorecard API

      - name: Upload results to GitHub Code Scanning
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: results.sarif
 