name: security

on: 
  pull_request:
  push:
    branches:
      - main
  workflow_dispatch:
    
permissions:
  contents: read
  security-events: write # needed to upload SARIF

concurrency:
  group: security-${{ github.ref }}
  cancel-in-progress: true

jobs:
  trivy-and-sbom:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # === Trivy Vuln + IaC scan (SARIF) ===
      - name: Trivy (vuln + config)
        uses: aquasecurity/trivy-action@0.24.0
        with:
          scan-type: fs
          scanners: "vuln,config"
          ignore-unfixed: true
          severity: "HIGH,CRITICAL"
          exit-code: 1    # fail the job on HIGH/CRITICAL
          format: "sarif"
          output: "trivy.sarif"
      
      - name: Upload SARIF
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: trivy.sarif

      # === SBOM (SPDX) via Trivy ===
      - name: Install Trivy CLI (for SBOM)
        run: |
          sudo apt-get update -y
          sudo apt-get install -y wget apt-transport-https gnupg lsb-release
          wget -qO - https://aquasecurity.github.io/trivy-repo/deb/public.key | sudo gpg --dearmor -o /usr/share/keyrings/trivy.gpg
          echo "deb [signed-by=/usr/share/keyrings/trivy.gpg] https://aquasecurity.github.io/trivy-repo/deb $(lsb_release -sc) main" | sudo tee /etc/apt/sources.list.d/trivy.list
          sudo apt-get update -y
          sudo apt-get install -y trivy

      - name: Generate SBOM (SPDX JSON)
        run: |
          trivy sbom --format spdx-json --output sbom.spdx.json dir:.

      - name: Upload SBOM artifact
        uses: actions/upload-artifact@v4
        with:
          name: sbom-spdx
          path: sbom.spdx.json